version: '3'

services:
  db:
    image: postgres:12
    container_name: opencms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  opencms:
    build: .
    container_name: opencms
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./tomcat_data:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/gabriel/desafio_vhl/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - opencms
  #update_hosts:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.script
  #  volumes:
  #    - /etc/hosts:/etc/hosts
  #  container_name: update-hosts-container
  #  entrypoint: ["/update_hosts.sh"]
  #  command: ["127.0.0.1", "opencms.potoco"]
  #  depends_on:
  #    - opencms