version: '3'

services:
  db:
    image: postgres:12
    container_name: opencms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  opencms:
    build: .
    container_name: opencms
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - tomcat_data:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - opencms

volumes:
  postgres_data:
  tomcat_data: